# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=12)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=12)),
                ('country_code', models.CharField(max_length=2)),
                ('open_weather_id', models.IntegerField()),
            ],
        ),
    ]
