# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notification', models.BooleanField(default=False)),
                ('max_temp', models.DecimalField(decimal_places=3, max_digits=7)),
                ('min_temp', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='UserCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('temp', models.DecimalField(decimal_places=3, max_digits=7)),
                ('max_temp', models.DecimalField(decimal_places=3, max_digits=7)),
                ('min_temp', models.DecimalField(decimal_places=3, max_digits=7)),
                ('pressure', models.DecimalField(decimal_places=3, max_digits=9)),
                ('wind_speed', models.DecimalField(decimal_places=3, max_digits=7)),
                ('wind_direction', models.DecimalField(decimal_places=3, max_digits=7)),
                ('clouds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculated', models.DateTimeField()),
                ('retrieved', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City')),
            ],
        ),
        migrations.AddField(
            model_name='temprange',
            name='user_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.UserCity'),
        ),
        migrations.AddField(
            model_name='notification',
            name='temp_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.TempRange'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Weather'),
        ),
        migrations.AddField(
            model_name='city',
            name='users',
            field=models.ManyToManyField(related_name='cities', through='weather.UserCity', to=settings.AUTH_USER_MODEL),
        ),
    ]
