# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20170301_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='users',
        ),
    ]
